# Generated by Django 3.1.4 on 2020-12-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
