# Generated by Django 3.1.4 on 2020-12-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20201230_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='bio'),
        ),
    ]
